#!/usr/bin/env python3
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import re
import sys
from html import unescape
from html.parser import HTMLParser
from pathlib import Path

try:
    from playwright.sync_api import sync_playwright, Error as PlaywrightError
except Exception:
    sync_playwright = None
    PlaywrightError = Exception

MOBILE_UA = (
    "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) "
    "AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 "
    "MicroMessenger/8.0.40(0x1800282e) NetType/WIFI Language/zh_CN"
)


class TextExtractor(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.skip = 0
        self.buf: list[str] = []
        self.skip_tags = {"script", "style", "noscript", "svg", "canvas"}

    def handle_starttag(self, tag, attrs):
        t = tag.lower()
        if t in self.skip_tags:
            self.skip += 1
        if t in {"p", "div", "section", "article", "br", "li", "h1", "h2", "h3", "h4"}:
            self.buf.append("\n")

    def handle_endtag(self, tag):
        t = tag.lower()
        if t in self.skip_tags and self.skip > 0:
            self.skip -= 1
        if t in {"p", "div", "section", "article", "li", "h1", "h2", "h3", "h4"}:
            self.buf.append("\n")

    def handle_data(self, data):
        if self.skip == 0:
            s = data.strip()
            if s:
                self.buf.append(s + " ")

    def text(self) -> str:
        text = unescape("".join(self.buf))
        text = re.sub(r"\n{3,}", "\n\n", text)
        text = re.sub(r"[ \t]{2,}", " ", text)
        return text.strip()


def looks_blocked(text: str) -> bool:
    s = text.lower()
    signals = [
        "captcha", "verify you are human", "access denied", "robot", "请先登录", "登录", "paywall", "权限"
    ]
    return any(x in s for x in signals)


def render_html(url: str, timeout_ms: int, headless: bool) -> str:
    if sync_playwright is None:
        raise RuntimeError("Playwright not installed. Run: pip install playwright && playwright install chromium")
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=headless)
        context = browser.new_context(
            user_agent=MOBILE_UA,
            viewport={"width": 414, "height": 896},
            extra_http_headers={
                "Accept-Language": "zh-CN,zh;q=0.9,en;q=0.8",
                "Referer": "https://mp.weixin.qq.com/",
            },
        )
        page = context.new_page()
        page.set_default_navigation_timeout(timeout_ms)
        page.goto(url, wait_until="networkidle", timeout=timeout_ms)
        for _ in range(6):
            page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            page.wait_for_timeout(200)
        page.wait_for_load_state("networkidle", timeout=timeout_ms)
        html = page.content()
        context.close()
        browser.close()
        return html


def build_filename(url: str) -> str:
    now = dt.datetime.now()
    ts = now.strftime("%Y%m%d%H%M%S")
    digest = hashlib.sha256(f"{url}-{ts}".encode()).hexdigest()[:10]
    return f"{ts}_{digest}.html"


def main() -> int:
    ap = argparse.ArgumentParser(description="Local-only webpage snapshot (pagecopy-like)")
    ap.add_argument("url")
    ap.add_argument("--out-dir", default=os.path.expanduser("~/.openclaw/pagecopy-local"))
    ap.add_argument("--timeout-seconds", type=float, default=45)
    ap.add_argument("--headful", action="store_true", help="run browser with UI (default headless)")
    args = ap.parse_args()

    out_dir = Path(args.out_dir).expanduser()
    out_dir.mkdir(parents=True, exist_ok=True)
    timeout_ms = int(args.timeout_seconds * 1000)

    try:
        html = render_html(args.url, timeout_ms=timeout_ms, headless=not args.headful)
        filename = build_filename(args.url)
        path = out_dir / filename
        captured_at = dt.datetime.now(dt.timezone.utc).isoformat()
        comment = (
            "<!--\n"
            f"Archived from: {args.url}\n"
            f"Captured at (UTC): {captured_at}\n"
            "Generated by local_snapshot.py\n"
            "-->\n"
        )
        path.write_text(comment + html, encoding="utf-8")

        parser = TextExtractor()
        parser.feed(html)
        text = parser.text()

        print(json.dumps({
            "ok": True,
            "local_path": str(path),
            "text_preview": text[:1200],
            "warning": "possible challenge/login/paywall" if looks_blocked(text) else None,
        }, ensure_ascii=False))
        return 0
    except PlaywrightError as e:
        print(json.dumps({"ok": False, "stage": "playwright", "error": str(e)}, ensure_ascii=False))
        return 2
    except Exception as e:
        print(json.dumps({"ok": False, "stage": "runtime", "error": str(e)}, ensure_ascii=False))
        return 3


if __name__ == "__main__":
    sys.exit(main())
